export const SCORE_BANDS = [
  {
    label: 'Excellent',
    range: '90–100',
    min: 90,
    max: 100,
    color: 'bg-status-pass',
    cssVar: 'var(--color-status-pass)',
    desc: 'Profile is highly optimized and follows best practices.',
  },
  {
    label: 'Very Good',
    range: '80–89',
    min: 80,
    max: 89,
    color: 'bg-status-pass',
    cssVar: 'var(--color-status-pass)',
    desc: 'Strong profile with only minor recommendations.',
  },
  {
    label: 'Good',
    range: '65–79',
    min: 65,
    max: 79,
    color: 'bg-status-warn',
    cssVar: 'var(--color-status-warn)',
    desc: 'Well optimized with noticeable room for improvement.',
  },
  {
    label: 'Fair',
    range: '50–64',
    min: 50,
    max: 64,
    color: 'bg-status-warn',
    cssVar: 'var(--color-status-warn)',
    desc: 'Profile is functional but requires several improvements.',
  },
  {
    label: 'Poor',
    range: '25–49',
    min: 25,
    max: 49,
    color: 'bg-status-fail',
    cssVar: 'var(--color-status-fail)',
    desc: 'Basic optimization exists, but many important elements are missing.',
  },
  {
    label: 'Critical',
    range: '0–24',
    min: 0,
    max: 24,
    color: 'bg-status-fail',
    cssVar: 'var(--color-status-fail)',
    desc: 'Major optimization issues detected.',
  },
];

export const WEIGHTED_RULES = [
  { id: 'rating', rule: 'Rating', weight: 30, priority: 'High' },
  { id: 'completeness', rule: 'Completeness', weight: 20, priority: 'High' },
  { id: 'business-category', rule: 'Business Category', weight: 15, priority: 'Medium' },
  { id: 'opening-hours', rule: 'Opening Hours', weight: 15, priority: 'Medium' },
  { id: 'business-status', rule: 'Business Status', weight: 10, priority: 'Medium' },
  { id: 'photos', rule: 'Photos', weight: 7, priority: 'Low' },
  { id: 'attributes', rule: 'Attributes', weight: 3, priority: 'Low' },
];
